### ISSUE TITLE
Can't work on Windows?

### ISSUE THREAD

**Issue by lauraset** [cmla/s2p#44]
Hello, cmla
    The s2p package only works on Mac or Linux system, and can't be used to Windows system. Is this possible to install gdal and s2p on Windows?

**Comment by carlodef** [comment]
Hello @lauraset,

As of now, `s2p` doesn't support Windows.

**Comment by gfacciol** [comment]
The best option to run from windows is using the Docker image https://hub.docker.com/r/cmla/s2p

**Comment by lauraset** [comment]
Thank you very much. @gfacciol. I have installed it on virtual machine.
