### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by franjamonga** [cmla/s2p#48]
Could you do a little tutorial on usage from a couple of satellite images? In other words, list the steps or command one by one used as well as the functionality of each one. It would be a great help

**Comment by gfacciol** [comment]
Thanks for the recommendation.
The example call below is not a tutorial, but it might help understanding
the usage of the pipeline.
The pipeline is run in a single command:

>  s2p tests/data/input_pair/config.json

you can take a look into the config file
https://github.com/cmla/s2p/blob/master/tests/data/input_pair/config.json

To understand the steps and the basic principles of a satellite pipeline we
developed a tutorial, which is available here:
https://gfacciol.github.io/IS18/
it does not use s2p directly, but the steps are the same.
