### ISSUE TITLE
STEREO PAIR IMAGES WITHOUT RPC POINTS

### ISSUE THREAD

**Issue by javierbecerra** [cmla/s2p#49]
Hello,
First of all, congrats for what you have done here. Really impressive. I have been trying to run it without RPC's and I always get a error. I am wondering if I am not able to run a process without that information (not always you're lucky enough to have RPC points). 
Thanks in advance!
Javier

**Comment by gfacciol** [comment]
Dear Javier, 
Unfortunately, if your images are reprojected products (e.g. ortho ready) there isn't  much we can do. Some images might have the rpc embedded in the geotiff, or ntf, in that case s2p can run even without the RPCs. You can use the gdalinfo command to display this embedded information, the RPCs are rather easy to see  (long sequences of 80 numbers).
 
Best, 
Gabriele
