### ISSUE TITLE
How to install two different versions of s2p?

### ISSUE THREAD

**Issue by lionlai1989** [cmla/s2p#55]
Hi:
Is it possible to install two different versions of s2p on my laptop?
My laptop now has MISS3D/s2p.https://github.com/MISS3D/s2p
But I want to try cmla/s2p without uninstall the MISS3D/s2p.
I first rename /usr/local/bin/s2p to /usr/local/bin/s2p_old, then I download the cmla/s2p. After, I modified the name entry in setup.py (cmla/s2p) to s2p-new and version entry, but it doesn't work out.
Any suggestion will be appreciated. Thank you very much.

**Comment by carlodef** [comment]
Hi @lionlai1989, a possible way of doing that would be to use virtual environments: https://docs.python.org/3/tutorial/venv.html

**Comment by lionlai1989** [comment]
Hi @carlodef Could you please explain more how to do it? I tried, but could not succeed. My steps are the following.
1. Create s2p_venv.
2. cd s2p_venv and activate s2p_venv.
3. Download cmla/s2p to s2p_venv.
4. cd  cmla/s2p and execute pip install -e .
5. But it still run the old s2p instead of the new one.
