### ISSUE TITLE
Visualization of Satellite (Camera) Positions

### ISSUE THREAD

**Issue by SBCV** [cmla/s2p#56]
While s2p computes a useful set of (point cloud related) outputs such as geo-registered DSM's, I could not find anything related to the corresponding camera poses. However, I've seen the following image on the [github.io page](https://gfacciol.github.io/multi-date-stereo/). 

Thus, I'm wondering, if this repository contains also some source code to generate these kind of images? If not, could you share some information, how this image has been created? 

Thank you in advance, and thank for sharing this wonderful library!

![footprints47_angles2](https://user-images.githubusercontent.com/19491335/86093473-4d786380-baaf-11ea-8b41-7820339ed213.jpg)

**Comment by gfacciol** [comment]
I can't find the code I used to produce this visualization, but it should
be easy to reproduce.

1. Use the RPCs to project a point on the ground of fixed coordinates (lat,
lon, alt) on every one of the images.
2. localize the projected points at altitude alt+1m, this gives a triplet
(lat',lon',alt+1m), the vectors from (lat, lon, alt) to  (lat',lon',alt+1m)
are the viewing directions
3. convert all lat,lon,alt coordinates to XYZ, and extend the vectors
corresponding to (lat',lon',alt+1m) until they are 700km
4. convert back the new XYZ coordinates.
5. write the kml file and open it with GoogleEarth

**Comment by SBCV** [comment]
Ty for the fast response
