### ISSUE TITLE
Stuck without output

### ISSUE THREAD

**Issue by waleedk745** [cmla/s2p#57]
The code has been running with following configurations for hours without output.
`{
  "out_dir" : "output_pair",
  "images" : [
    {"img" : "12FEB16101327-P1BS-056082198020_01_P001.TIF"},
    {"img" : "12FEB16101426-P1BS-056082198020_01_P001.TIF"}
    ],
  "roi": {
	"x": 17.82351,
	"y": 59.32518,
	"h": 1000,
	"w": 1000
  },
  "tile_size" : 500,
  "max_processes": 6,
  "disp_range_method" : "sift",
  "msk_erosion": 0,
  "dsm_resolution": 0.5,
  "debug": true
}`
The images used are from the following source [https://www.maxar.com/product-samples](url)
The output log is as follows:
`root@522a04de473c:~/input_pair# s2p config.json 
WARNING: out_dir is a relative path. It is interpreted with respect to config.json location (not cwd)
out_dir is: /root/input_pair/output_pair
tile size: 1000 1000
total number of tiles: 25 (5 x 5)
discarding masked tiles...
done 25 / 25 tiles
Elapsed time: 0:00:04.593081
correcting pointing locally...
correcting pointing on tile 17 59 pair 1...
correcting pointing on tile 4017 59 pair 1...
correcting pointing on tile 2017 59 pair 1...
correcting pointing on tile 3017 59 pair 1...
correcting pointing on tile 1017 59 pair 1...
correcting pointing on tile 17 1059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 1017 1059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 2017 1059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 3017 1059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 4017 1059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 17 2059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 1017 2059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 2017 2059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 3017 2059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 4017 2059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 17 3059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 1017 3059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 2017 3059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 3017 3059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 4017 3059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 17 4059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 1017 4059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 2017 4059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 3017 4059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
correcting pointing on tile 4017 4059 pair 1...
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
WARNING: returning coarse range from rpc
RUN: gdal_translate -ot Float32 -co TILED=YES -co BIGTIFF=IF_NEEDED -srcwin 1017 3059 1000 1000 '/root/input_pair/12FEB16101327-P1BS-056082198020_01_P001.TIF' '/root/input_pair/s2p_tmp/s2p_chjiuq49.tif'
Input file size is 35180, 12060
0...10...20...30...40...50...60...70...80...90...100 - done.
0:00:00.470664
RUN: qauto /root/input_pair/s2p_tmp/s2p_chjiuq49.tif /root/input_pair/s2p_tmp/s2p_1ijg5j_v.png
0:00:00.311370
RUN: gdal_translate -ot Float32 -co TILED=YES -co BIGTIFF=IF_NEEDED -srcwin 1419 4364 1403 2220 '/root/input_pair/12FEB16101426-P1BS-056082198020_01_P001.TIF' '/root/input_pair/s2p_tmp/s2p_w0od8wwd.tif'
Input file size is 35180, 10940
0...10...20...30...40...50...60...70...80...90...100 - done.
0:00:00.717702
RUN: qauto /root/input_pair/s2p_tmp/s2p_w0od8wwd.tif /root/input_pair/s2p_tmp/s2p_bpay3x9d.png
0:00:00.901748
RUN: cp /root/input_pair/s2p_tmp/s2p_7oyuikux.png /root/input_pair/output_pair/tiles/row_0003059_height_1000/col_0001017_width_1000/pair_1/sift_matches_pointing.png
0:00:01.023354
done  1 / 25 tile`

I have tried changing the ROI without any luck.

**Comment by carlodef** [comment]
Hi @waleedk745, the `x` and `y` keys of the `roi` dict in the input `json` configuration are pixel coordinates. I have the impression that your values of `17.82351` and `59.32518` look like geographic coordinates, is that correct?
