### ISSUE TITLE
Command 's2p' not found

### ISSUE THREAD

**Issue by zongchengzuo** [cmla/s2p#59]
Hi Guys, great job!

I executed `pip3 install s2p` on Ubuntu 18.04.4, and prompted that `s2p` was successfully installed, but when I entered `sep -h`, the command 's2p' not found was thrown. Thanks.

![s2p01](https://user-images.githubusercontent.com/15527594/90112252-53d24e80-dd82-11ea-8806-7bc50ebd11c1.JPG)

**Comment by carlodef** [comment]
Hi @zongchengzuo, your `$PATH` is probably missing the directory where `pip` puts binaries. Usually it's in `/usr/local/bin`. You can try 

    ls $(python3 -m site --user-base)/bin/

and check if `s2p` is there. If yes you should add the value of `$(python3 -m site --user-base)/bin` to your `PATH`.

**Comment by zongchengzuo** [comment]
It works, thanks a lot.
