### ISSUE TITLE
I can't successfully run the "make test?

### ISSUE THREAD

**Issue by yueluming** [cmla/s2p#62]
make -j -C 3rdparty/homography
make[1]: 进入目录“/home/yzy/Desktop/s2p/yueluming-s2p-master（ubantu18）/s2p/3rdparty/homography”
make[1]: *** 没有指明目标并且找不到 makefile。 停止。
make[1]: 离开目录“/home/yzy/Desktop/s2p/yueluming-s2p-master（ubantu18）/s2p/3rdparty/homography”
makefile:26: recipe for target 'homography' failed
make: *** [homography] Error 2

**Comment by gfacciol** [comment]
You're missing the submodules. You clone the repository with the --recursive option
     
     git clone https://github.com/cmla/s2p.git --recursive

If the --recursive option wasn't used when cloning, the submodules they can be retrieved with

     git submodule update --init

**Comment by yueluming** [comment]
> You're missing the submodules. You clone the repository with the --recursive option
> 
> ```
>  git clone https://github.com/cmla/s2p.git --recursive
> ```
> 
> If the --recursive option wasn't used when cloning, the submodules they can be retrieved with
> 
> ```
>  git submodule update --init
> ```

Thanks
