### ISSUE TITLE
I want to run "['matching_algorithm'] = 'sgbm'",but the error is coming .FileNotFoundError: [Errno 2] No such file or directory: 'sgbm': 'sgbm'

### ISSUE THREAD

**Issue by yueluming** [cmla/s2p#65]

**Comment by carlodef** [comment]
You need to compile it with `make all`, after cloning the repository in recursive mode. The default makefile rule doesn't compile every optional stereo matching code.

**Comment by yueluming** [comment]
> You need to compile it with `make all`, after cloning the repository in recursive mode. The default makefile rule doesn't compile all the optional stereo matching algorithms.

I am studying this code, and  I want to try to run "'input_ply' and 'units'" in the tests/data, what kind of command should I use?

**Comment by carlodef** [comment]
You can run the tests with `pytest tests` at the root of the repository

**Comment by limiao766** [comment]
> `make all`在以递归模式克隆存储库后，您需要使用 , 来编译它。默认的 makefile 规则不会编译所有可选的立体匹配算法。

How to change can use 'sgbm'.
