### ISSUE TITLE
How to change the number of using gpus?

### ISSUE THREAD

**Issue by yueluming** [cmla/s2p#67]
When I use this code to process  large images, it comes with this error, "subprocess.CalledProcessError: Command '['mgm', '-r', '-22', '-R', '48', '-s', 'vfit', '-t', 'census', '-O', '8', '-confidence_consensusL',..................died with <Signals.SIGKILL: 9>."

**Comment by carlodef** [comment]
`s2p` doesn't use GPUs. Your error is likely due to running out of memory. To reduce the memory footprint, you can limit the number of parallel stereo matching runs by setting `max_processes_stereo_matching` to 1 in the input json configuration file.

**Comment by yueluming** [comment]
> `s2p` doesn't use GPUs. Your error is likely due to running out of memory. To reduce the memory footprint, you can limit the number of parallel stereo matching runs by setting `max_processes_stereo_matching` to 1 in the input json configuration file.

Thanks!
