### ISSUE TITLE
Why the in_crs=4326, out_crs=4978?

### ISSUE THREAD

**Issue by yueluming** [cmla/s2p#70]
def lonlat_to_geocentric(lon, lat, alt):
    """
    Compute geocentric cartesian coordinates of a given lon, lat, alt point.

    Args:
        lon (float or list): longitude(s)
        lat (float or list): latitude(s)
        alt (float or list): latitude(s)

    Returns:
        three floats or three lists of floats
    """
    x, y, z = pyproj_transform(lon, lat, 4326, 4978, alt)
    return x, y, z

**Comment by gfacciol** [comment]
epsg 4326 is an ellipsoidal coordinate system: latitude, longitude, altitude
epsg 4978 is a geocentric cartesian system with coordinates: X,Y,Z
this function converts from WGS84 (lonlat)  to geocentric coordinates

**Comment by yueluming** [comment]
> epsg 4326 is an ellipsoidal coordinate system: latitude, longitude, altitude
> epsg 4978 is a geocentric cartesian system with coordinates: X,Y,Z
> this function converts from WGS84 (lonlat) to geocentric coordinates

Thanks!
