### ISSUE TITLE
Make test failed 

### ISSUE THREAD

**Issue by tobkug** [cmla/s2p#73]
Hi

I'm facing the following 2 errors when I'm doing `make test`. Thanks for providing help.
 
> ====================== short test summary info===============================================
> FAILED tests/common_test.py::test_run_timeout - AssertionError: assert 'sleep' not in ['init', 'kthreadd', 'rcu_gp', 'rcu_par_gp', 'kworker/0:0-events', 'kworker/0:0H-kblockd', ...]
> FAILED tests/rpc_utils_test.py::test_roi_process[True-None-True-expected1] - requests.exceptions.ConnectionError: HTTPConnectionPool(host='data.cgiar-csi.org', port=80): Max retries exceeded with ur...
> ================ 2 failed, 31 passed, 1 warning in 958.28s (0:15:58)=================================

And here the full terminal output:
[Make test.txt](https://github.com/cmla/s2p/files/5322861/Make.test.txt)

**Comment by carlodef** [comment]
Hi, you need to update `srtm4` with

    pip install -U srtm4

**Comment by tobkug** [comment]
Great, that helped. But the error in `common_test.py` remains.

Nevertheless, I managed to process some images from the IARPA dataset.
