### ISSUE TITLE
Specify the projected coordinate system

### ISSUE THREAD

**Issue by zongchengzuo** [cmla/s2p#74]
Hi, I found that the default projection coordinates of the generated DSM is the Transverse Mercator projection (ie Gausske Rüger projection). Can I specify the projected coordinate system of the generated DSM?

**Comment by carlodef** [comment]
You can specify the output coordinate reference system with the `out_crs` key of the input `json` configuration file. All formats accepted by `pyproj.CRS()` are allowed.

More info in this comment: https://github.com/cmla/s2p/blob/master/s2p/config.py#L160-L166
