### ISSUE TITLE
How to bring IARPA rpc files in a valid form?

### ISSUE THREAD

**Issue by tobkug** [cmla/s2p#76]
Hi

I'm trying to use the already cropped IARPA tif. images like it's been done here [Automatic 3D Reconstruction from Multi-Date Satellite Images](https://gfacciol.github.io/multi-date-stereo/)

How can I convert the included rpc txt. files into a valid form, in order that s2p can read it? The provided rpc data consists only of comma separated values.

![image](https://user-images.githubusercontent.com/72332224/95673735-b80b6600-0bab-11eb-872b-1f3d372e1049.png)

**Comment by tobkug** [comment]
I prepared them in IKONOS style. 
Now "ERROR: the ROI is not seen in two images or is totally masked" occurs, although `full_img` is set to true

config:
```

{
  "out_dir" : "../Output/WV3/TestCropped",
  "images" : [
    { "img": "Challenge1_LowRiseBuildings_CROPPED_02APR15WV031000015APR02134718-P1BS-500497282050_01_P001_________AAE_0AAAAABPABJ0.tif",
      "rpc": "rpc_Challenge1_LowRiseBuildings_CROPPED_02APR15WV031000015APR02134718-P1BS-500497282050_01_P001_________AAE_0AAAAABPABJ0.txt"},
    { "img": "Challenge1_LowRiseBuildings_CROPPED_02APR15WV031000015APR02134716-P1BS-500276959010_02_P001_________AAE_0AAAAABPABB0.tif",
      "rpc": "rpc_Challenge1_LowRiseBuildings_CROPPED_02APR15WV031000015APR02134716-P1BS-500276959010_02_P001_________AAE_0AAAAABPABB0.txt"}
    ],
  "roi" : {
      "x" : 1000,
      "y" : 1000,
      "w" : 500,
      "h" : 500
  },
  "full_img": true,
  "horizontal_margin": 20,
  "vertical_margin": 5,
  "tile_size" : 500,
  "disp_range_method" : "sift",
  "msk_erosion": 0,
  "dsm_resolution": 0.5,
  "max_processes": 1,
  "max_processes_stereo_matching": 1
}

```

**Comment by gfacciol** [comment]
Hi, the roi option is ignored when full_img is true.  
Have you tried removing the roi entry? do you still get an empty result?

**Comment by tobkug** [comment]
Yes, still the same when I'am removing the roi entry. Any idea?
