### ISSUE TITLE
The parameter "utm_bbx"

### ISSUE THREAD

**Issue by lien-hub** [cmla/s2p#87]
Hi! Here some questions about "utm_bbx"?
1. What is the function of "utm_bbx"?
2. how does it calculate for a new image?
Looking forward for your responding! Thank you!

**Comment by carlodef** [comment]
There is no parameter named "utm_box". What are you referring to?

**Comment by lien-hub** [comment]
> There is no parameter named "utm_box". What are you referring to?

I'm sorry for my error in the title. It's the parameter named "utm_bbx",in "s2p/tests/data/input_pair/config.json".
